# Generated by Django 5.0.6 on 2024-08-16 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.blog')),
            ],
        ),
    ]
