# Generated by Django 5.0.6 on 2024-08-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_drafts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
