# Generated by Django 5.0.6 on 2024-08-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='blogs')),
                ('Category', models.CharField(max_length=50)),
                ('Summary', models.TextField()),
                ('Content', models.TextField()),
            ],
        ),
    ]
